# Generated by Django 2.2.6 on 2019-10-29 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Merchandise',
            new_name='Product',
        ),
    ]
