# Generated by Django 2.2.6 on 2019-10-31 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191029_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=300)),
                ('Picture', models.ImageField(upload_to='CategoryImages')),
                ('Active', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='Picture',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='ProductSKU',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='designer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='AvailableColor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='AvailableSize',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='Color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='Discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='MSRP',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Note',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ProductDescription',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ProductName',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='QuantityPerUnit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Ranking',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ReorderLevel',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='UnitPrice',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='UnitWeight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='UnitsInStock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='UnitsOnOrder',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='CategoryID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Category'),
        ),
    ]
